parameters:
    docga_extended_attribute_type.array_converter.flat_to_standard.docga.class: Oniti\Docga\ConnectorBundle\ArrayConverter\FlatToStandard\Product\ValueConverter\DocgaConverter
    docga_extended_attribute_type.array_converter.standard_to_flat.docga.class: Oniti\Docga\ConnectorBundle\ArrayConverter\StandardToFlat\Product\ValueConverter\DocgaConverter

services:
    docga_extended_attribute_type.array_converter.standard_to_flat.product.value_converter.docga:
        class: '%docga_extended_attribute_type.array_converter.standard_to_flat.docga.class%'
        arguments:
            - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
            - ['pim_catalog_docga']
        tags:
            - { name: 'pim_connector.array_converter.standard_to_flat.product.value_converter' }

    docga_extended_attribute_type.array_converter.flat_to_standard.product.value_converter.docga:
        class: '%docga_extended_attribute_type.array_converter.flat_to_standard.docga.class%'
        arguments:
            - ['pim_catalog_docga']
        tags:
            - { name: 'pim_connector.array_converter.flat_to_standard.product.value_converter' }
