parameters:
    docga_extended_attribute_type.attribute_type.docga.class: Oniti\Docga\ConnectorBundle\AttributeType\DocgaType

services:
    docga_extended_attribute_type.attribute_type.docga:
        class: '%docga_extended_attribute_type.attribute_type.docga.class%'
        arguments:
            - text
            - text
            - '@pim_catalog.validator.constraint_guesser.chained_attribute'
        tags:
            - { name: pim_catalog.attribute_type, alias: pim_catalog_docga }
