parameters:
    docga_extended_attribute_type.completeness.checker.docga.class:  Oniti\Docga\ConnectorBundle\Completeness\Checker\DocgaCompleteChecker

services:
    docga_extended_attribute_type.completeness.checker.docga:
        class: '%docga_extended_attribute_type.completeness.checker.docga.class%'
        tags:
            - { name: pim_catalog.completeness.checker.product_value, priority: 100 }
