parameters:
    docga_extended_attribute_type.denormalizer.flat.docga.class: Oniti\Docga\ConnectorBundle\Normalizer\Flat\DocgaDenormalizerFlat
    docga_extended_attribute_type.normalizer.indexing_product.product.docga.class: Oniti\Docga\ConnectorBundle\Normalizer\Indexing\Value\DocgaNormalizer

services:
    docga_extended_attribute_type.denormalizer.flat.docga:
        class: '%docga_extended_attribute_type.denormalizer.flat.docga.class%'
        arguments:
            - ['pim_catalog_docga']
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }


    docga_extended_attribute_type.normalizer.indexing_product.product.docga:
        class: '%docga_extended_attribute_type.normalizer.indexing_product.product.docga.class%'
        arguments:
            - '@pim_catalog.repository.cached_attribute'
        tags:
            - { name: pim_serializer.normalizer, priority: 150 }
            - { name: pim_internal_api_serializer.normalizer, priority: 150 }
