parameters:
    pim_filter.form.type.docga.class: Oniti\Docga\ConnectorBundle\DataGrid\Form\Type\Filter\DocgaFilterType

services:
    pim_filter.form.type.docga:
        class: '%pim_filter.form.type.docga.class%'
        arguments:
            - '@translator'
        tags:
            - { name: form.type, alias: pim_type_docga_filter }
