parameters:
    docga_extended_attribute_type.provider.field.docga.class: Oniti\Docga\ConnectorBundle\Provider\Field\DocgaProvider
    docga_extended_attribute_type.provider.filter.class: Oniti\Docga\ConnectorBundle\Filter\FilterProvider

services:
    docga_extended_attribute_type.provider.field.docga:
        class: '%docga_extended_attribute_type.provider.field.docga.class%'
        tags:
            - { name: pim_enrich.provider.field, priority: 100 }

    docga_extended_attribute_type.provider.filter:
        class: '%docga_extended_attribute_type.provider.filter.class%'
        tags:
            - { name: pim_enrich.provider.filter, priority: 100 }

