config:
#    shim:
#        docga-api:
#            exports: docga-extended-attribute-type/docga-api
#        docga-extended-attribute-type/docga-field:
#            deps:
#                - docga-api
#            exports: docgaextendedattributetype/js/product/field/docga-field
    paths:
        docga-extended-attribute-type/docga-field: docgaextendedattributetype/js/product/field/docga-field
        docga-extended-attribute-type/templates/product/field/docga: docgaextendedattributetype/templates/product/field/docga-field.html
        docga-extended-attribute-type/templates/datagrid/cell/docga: docgaextendedattributetype/templates/datagrid/cell/docga.html
        oro/datagrid/docga-cell: docgaextendedattributetype/js/datagrid/cell/docga-cell
        docga-extended-attribute-type/configuration/tab: docgaextendedattributetype/js/configuration/tab
        docga-extended-attribute-type/configuration/tab-template: docgaextendedattributetype/templates/system/group/configuration.html
        docga-extended-attribute-type/docga-api: docgaextendedattributetype/js/product/field/docga_api

    config:
        pim/form/common/attributes/create-button:
            attribute_icons:
                pim_catalog_docga: assetCollection

        pim/attribute-edit-form/type-specific-form-registry:
            formNames:
                pim_catalog_docga:
                    create: pim-attribute-form-text
                    edit:   pim-attribute-form-text
