services:
    pim_catalog.updater.setter.docga_value:
        public: false
        class: '%pim_catalog.updater.setter.value.class%'
        parent: pim_catalog.updater.setter.abstract
        arguments:
            - [!php/const:\Oniti\Docga\ConnectorBundle\AttributeType\ExtendedAttributeTypes::DOCGA]
        tags:
            - { name: 'pim_catalog.updater.setter' }

    pim_catalog.updater.copier.docga_value:
        public: false
        class: '%pim_catalog.updater.copier.value.class%'
        parent: pim_catalog.updater.copier.abstract
        arguments:
            - '@pim_serializer'
            - [!php/const:\Oniti\Docga\ConnectorBundle\AttributeType\ExtendedAttributeTypes::DOCGA]
            - [!php/const:\Oniti\Docga\ConnectorBundle\AttributeType\ExtendedAttributeTypes::DOCGA]
        tags:
            - { name: 'pim_catalog.updater.copier' }
